use longhorn_command::CommandTextInputPolicy;

mod panel_specs;
mod registry;
mod route;

use panel_specs::PANEL_COMMAND_SPECS;
pub(super) use registry::build_registry;
pub(crate) use route::NucleusCommandRoute;

pub(super) struct CommandSpec {
    pub(super) id: &'static str,
    pub(super) label: &'static str,
    pub(super) description: &'static str,
    pub(super) category: &'static str,
    pub(super) keywords: &'static [&'static str],
    pub(super) context: &'static str,
    pub(super) capability: &'static str,
    pub(super) route: NucleusCommandRoute,
    pub(super) text_input_policy: CommandTextInputPolicy,
}

const BLOCKED: CommandTextInputPolicy = CommandTextInputPolicy::Blocked;
const ALLOWED: CommandTextInputPolicy = CommandTextInputPolicy::Allowed;

pub(super) const COMMAND_SPECS: &[CommandSpec] = &[
    spec(
        "nucleus:shell.show-command-palette",
        "Show Command Palette",
        "Search and run admitted Nucleus commands.",
        "shell",
        &["commands", "actions"],
        "global",
        "nucleus:shell",
        NucleusCommandRoute::ShowCommandPalette,
        ALLOWED,
    ),
    spec(
        "nucleus:shell.open-settings",
        "Open Settings",
        "Open application Settings.",
        "shell",
        &["preferences"],
        "global",
        "nucleus:shell",
        NucleusCommandRoute::OpenSettings,
        ALLOWED,
    ),
    spec(
        "nucleus:project.create",
        "Create Project",
        "Create a project record.",
        "projects",
        &["new"],
        "workspace",
        "nucleus:projects",
        NucleusCommandRoute::CreateProject,
        BLOCKED,
    ),
    spec(
        "nucleus:project.manage",
        "Manage Projects",
        "Open project lifecycle management.",
        "projects",
        &["parked", "archived"],
        "workspace",
        "nucleus:projects",
        NucleusCommandRoute::ManageProjects,
        BLOCKED,
    ),
    spec(
        "nucleus:project.refresh",
        "Refresh Projects",
        "Reload project records and resources.",
        "projects",
        &["reload"],
        "workspace",
        "nucleus:projects",
        NucleusCommandRoute::RefreshProjects,
        BLOCKED,
    ),
    spec(
        "nucleus:sidebar.show-projects",
        "Show Projects",
        "Select the Projects sidebar view.",
        "navigation",
        &["sidebar"],
        "workspace",
        "nucleus:shell",
        NucleusCommandRoute::ShowProjects,
        BLOCKED,
    ),
    spec(
        "nucleus:sidebar.show-threads",
        "Show Threads",
        "Select the Threads sidebar view.",
        "navigation",
        &["sidebar", "chat"],
        "workspace",
        "nucleus:shell",
        NucleusCommandRoute::ShowThreads,
        BLOCKED,
    ),
    spec(
        "nucleus:sidebar.show-files",
        "Show Files",
        "Select the Files sidebar view.",
        "navigation",
        &["sidebar", "tree"],
        "workspace",
        "nucleus:shell",
        NucleusCommandRoute::ShowFiles,
        BLOCKED,
    ),
    spec(
        "nucleus:sidebar.show-forge",
        "Show Forge",
        "Select the Forge sidebar view.",
        "navigation",
        &["sidebar", "git"],
        "workspace",
        "nucleus:shell",
        NucleusCommandRoute::ShowForge,
        BLOCKED,
    ),
    spec(
        "nucleus:project.rename-selected",
        "Rename Project",
        "Rename the selected project inline.",
        "projects",
        &["name"],
        "project",
        "nucleus:projects",
        NucleusCommandRoute::RenameSelectedProject,
        BLOCKED,
    ),
    spec(
        "nucleus:project.manage-resources",
        "Manage Project Resources",
        "Open resources for the selected project.",
        "projects",
        &["repository", "folder"],
        "project",
        "nucleus:projects",
        NucleusCommandRoute::ManageProjectResources,
        BLOCKED,
    ),
    spec(
        "nucleus:project.park-selected",
        "Park Project",
        "Remove the selected project from the active rail.",
        "projects",
        &["lifecycle"],
        "project",
        "nucleus:projects",
        NucleusCommandRoute::ParkSelectedProject,
        BLOCKED,
    ),
    spec(
        "nucleus:project.archive-selected",
        "Archive Project",
        "Archive the selected project.",
        "projects",
        &["lifecycle"],
        "project",
        "nucleus:projects",
        NucleusCommandRoute::ArchiveSelectedProject,
        BLOCKED,
    ),
    spec(
        "nucleus:thread.rename-active",
        "Rename Thread",
        "Rename the active Agent Chat thread inline.",
        "threads",
        &["chat", "name"],
        "agent-chat",
        "nucleus:threads",
        NucleusCommandRoute::RenameActiveThread,
        BLOCKED,
    ),
    spec(
        "nucleus:thread.convert-to-project",
        "Convert Thread To Project",
        "Promote the active ephemeral thread into a project.",
        "threads",
        &["chat", "promote"],
        "agent-chat",
        "nucleus:threads",
        NucleusCommandRoute::ConvertThreadToProject,
        BLOCKED,
    ),
    spec(
        "nucleus:editor.quick-open",
        "Quick Open File",
        "Search admitted project files from the active editor.",
        "editor",
        &["file", "search"],
        "editor",
        "nucleus:editor",
        NucleusCommandRoute::QuickOpenFile,
        ALLOWED,
    ),
    spec(
        "nucleus:editor.save",
        "Save File",
        "Save the active dirty editor buffer.",
        "editor",
        &["write"],
        "editor",
        "nucleus:editor",
        NucleusCommandRoute::SaveEditorFile,
        ALLOWED,
    ),
    spec(
        "nucleus:forge.refresh",
        "Refresh Forge",
        "Reload current working-copy state.",
        "forge",
        &["git", "status"],
        "forge",
        "nucleus:forge",
        NucleusCommandRoute::RefreshForge,
        BLOCKED,
    ),
    spec(
        "nucleus:agent.cancel-turn",
        "Cancel Agent Turn",
        "Cancel the active Agent Chat turn.",
        "agent",
        &["stop", "interrupt"],
        "agent-chat",
        "nucleus:agent-turns",
        NucleusCommandRoute::CancelAgentTurn,
        ALLOWED,
    ),
];

pub(super) const COMMAND_SPEC_GROUPS: &[&[CommandSpec]] = &[COMMAND_SPECS, PANEL_COMMAND_SPECS];

const fn spec(
    id: &'static str,
    label: &'static str,
    description: &'static str,
    category: &'static str,
    keywords: &'static [&'static str],
    context: &'static str,
    capability: &'static str,
    route: NucleusCommandRoute,
    text_input_policy: CommandTextInputPolicy,
) -> CommandSpec {
    CommandSpec {
        id,
        label,
        description,
        category,
        keywords,
        context,
        capability,
        route,
        text_input_policy,
    }
}
