use super::{spec, CommandSpec, NucleusCommandRoute, BLOCKED};

pub(super) const PANEL_COMMAND_SPECS: &[CommandSpec] = &[
    spec(
        "nucleus:panel.open-agent-chat",
        "Open Agent Chat",
        "Open an Agent Chat panel in the current project.",
        "panels",
        &["chat", "agent"],
        "project",
        "nucleus:panels",
        NucleusCommandRoute::OpenAgentChatPanel,
        BLOCKED,
    ),
    spec(
        "nucleus:panel.open-browser",
        "Open Browser",
        "Open a Browser panel in the current project.",
        "panels",
        &["web"],
        "project",
        "nucleus:panels",
        NucleusCommandRoute::OpenBrowserPanel,
        BLOCKED,
    ),
    spec(
        "nucleus:panel.open-editor",
        "Open Editor",
        "Open an Editor panel in the current project.",
        "panels",
        &["code", "file"],
        "project",
        "nucleus:panels",
        NucleusCommandRoute::OpenEditorPanel,
        BLOCKED,
    ),
    spec(
        "nucleus:panel.open-terminal",
        "Open Terminal",
        "Open a host-routed Terminal panel.",
        "panels",
        &["shell"],
        "project",
        "nucleus:panels",
        NucleusCommandRoute::OpenTerminalPanel,
        BLOCKED,
    ),
    spec(
        "nucleus:panel.open-tasks",
        "Open Tasks",
        "Open the singleton Tasks panel.",
        "panels",
        &["goals"],
        "project",
        "nucleus:panels",
        NucleusCommandRoute::OpenTasksPanel,
        BLOCKED,
    ),
    spec(
        "nucleus:panel.open-diff",
        "Open Diff",
        "Open a Diff review panel.",
        "panels",
        &["review", "changes"],
        "project",
        "nucleus:panels",
        NucleusCommandRoute::OpenDiffPanel,
        BLOCKED,
    ),
    spec(
        "nucleus:panel.open-memory",
        "Open Memory",
        "Open the project Memory panel.",
        "panels",
        &["context"],
        "project",
        "nucleus:panels",
        NucleusCommandRoute::OpenMemoryPanel,
        BLOCKED,
    ),
    spec(
        "nucleus:panel.close-active",
        "Close Active Panel",
        "Close the active workspace panel.",
        "panels",
        &["tab"],
        "panel",
        "nucleus:panels",
        NucleusCommandRoute::CloseActivePanel,
        BLOCKED,
    ),
];
