use nucleus_memory::{
    AcceptedMemoryReviewReceiptAdmissionStatusStorage, AcceptedMemoryReviewReceiptDecisionStorage,
    AcceptedMemoryReviewReceiptStatusStorage, AcceptedMemoryReviewReceiptStorageRecord,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AcceptedMemoryActiveApplyAdmissionInput {
    pub request_id: String,
    pub operator_ref: String,
    pub approval_ref: String,
    pub expected_apply_admission_ref: String,
    pub expected_import_admission_ref: String,
    pub expected_conflict_ref: String,
    pub expected_candidate_ref: String,
    pub expected_memory_id: String,
    pub expected_file_ref: String,
    pub provenance_refs: Vec<String>,
    pub evidence_refs: Vec<String>,
    pub review_receipt: AcceptedMemoryReviewReceiptStorageRecord,
    pub raw_payload_present: bool,
    pub active_memory_mutation_requested: bool,
    pub projection_write_requested: bool,
    pub scm_effect_requested: bool,
    pub embedding_requested: bool,
    pub provider_sync_requested: bool,
    pub automatic_extraction_requested: bool,
    pub task_mutation_requested: bool,
    pub agent_scheduling_requested: bool,
    pub ui_effect_requested: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AcceptedMemoryActiveApplyAdmissionSet {
    pub records: Vec<AcceptedMemoryActiveApplyAdmissionRecord>,
    pub counts: AcceptedMemoryActiveApplyAdmissionCounts,
    pub active_memory_apply_performed: bool,
    pub projection_write_performed: bool,
    pub scm_effect_performed: bool,
    pub embedding_available: bool,
    pub provider_sync_available: bool,
    pub automatic_extraction_performed: bool,
    pub task_mutation_performed: bool,
    pub agent_scheduling_performed: bool,
    pub ui_effect_performed: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AcceptedMemoryActiveApplyAdmissionRecord {
    pub active_apply_admission_ref: String,
    pub request_id: String,
    pub review_receipt_id: String,
    pub project_id: String,
    pub command_id: String,
    pub apply_admission_ref: String,
    pub import_admission_ref: String,
    pub conflict_ref: String,
    pub candidate_ref: String,
    pub memory_id: String,
    pub file_ref: String,
    pub operator_ref: String,
    pub approval_ref: String,
    pub review_operator_ref: String,
    pub review_approval_ref: Option<String>,
    pub provenance_refs: Vec<String>,
    pub evidence_refs: Vec<String>,
    pub review_decision: AcceptedMemoryReviewReceiptDecisionStorage,
    pub review_status: AcceptedMemoryReviewReceiptStatusStorage,
    pub review_admission_status: AcceptedMemoryReviewReceiptAdmissionStatusStorage,
    pub status: AcceptedMemoryActiveApplyAdmissionStatus,
    pub blockers: Vec<AcceptedMemoryActiveApplyAdmissionBlocker>,
    pub active_memory_apply_performed: bool,
    pub projection_write_performed: bool,
    pub scm_effect_performed: bool,
    pub embedding_available: bool,
    pub provider_sync_available: bool,
    pub automatic_extraction_performed: bool,
    pub task_mutation_performed: bool,
    pub agent_scheduling_performed: bool,
    pub ui_effect_performed: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AcceptedMemoryActiveApplyAdmissionStatus {
    Admitted,
    DuplicateNoop,
    Blocked,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AcceptedMemoryActiveApplyAdmissionBlocker {
    MissingRequestId,
    MissingOperatorRef,
    MissingApprovalRef,
    MissingReviewReceiptId,
    MissingReviewApprovalRef,
    MissingApplyAdmissionRef,
    MissingImportAdmissionRef,
    MissingConflictRef,
    MissingCandidateRef,
    MissingMemoryId,
    MissingFileRef,
    MissingProvenanceRefs,
    MissingEvidenceRefs,
    ReviewNotApproved,
    ReviewDeferred,
    ReviewRejected,
    ReviewBlocked,
    ReviewAdmissionDuplicateNoop,
    ReviewAdmissionBlocked,
    ReviewBlockersPresent,
    AdmissionBlockersPresent,
    StaleApplyAdmissionRef,
    StaleImportAdmissionRef,
    StaleConflictRef,
    StaleCandidateRef,
    StaleMemoryId,
    StaleFileRef,
    StaleProvenanceRefs,
    StaleEvidenceRefs,
    RawPayloadPresent,
    ActiveMemoryMutationRequested,
    ProjectionWriteRequested,
    ScmEffectRequested,
    EmbeddingRequested,
    ProviderSyncRequested,
    AutomaticExtractionRequested,
    TaskMutationRequested,
    AgentSchedulingRequested,
    UiEffectRequested,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AcceptedMemoryActiveApplyAdmissionCounts {
    pub inputs: usize,
    pub admitted: usize,
    pub duplicate_noops: usize,
    pub blocked: usize,
    pub blockers: usize,
    pub missing_ref_blockers: usize,
    pub review_state_blockers: usize,
    pub stale_ref_blockers: usize,
    pub raw_payload_blockers: usize,
    pub effect_blockers: usize,
}
