// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Codex observation visible to diagnostics clients.
 */
export type CodexIngestionObservationDiagnosticDto = { source_id: string, binding_id: string, task_id: string, work_item_id: string, status: string, event_store_event_id: string | null, receipt_id: string | null, evidence_refs: Array<string>, next_action: string, permits_task_state_mutation: boolean, summary: string, };
