// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recovery execution attempt visible to diagnostics clients.
 */
export type CodexRecoveryExecutionAttemptDiagnosticDto = { need_id: string, envelope_id: string, provider_thread_id: string, provider_turn_id: string | null, provider_request_id: string | null, task_id: string, work_item_id: string, admission_id: string | null, policy_id: string | null, live_executor_outcome_id: string | null, runtime_receipt_id: string | null, provider_instance_id: string, recovery_write_attempt_id: string | null, status: string, blockers: Array<string>, runtime_progress: string | null, recovery_refs: Array<string>, evidence_refs: Array<string>, provider_completion_recorded: boolean, provider_write_recorded: boolean, replacement_thread_observed: boolean, task_completion_permitted: boolean, review_acceptance_permitted: boolean, replacement_thread_promotion_permitted: boolean, interruption_permitted: boolean, callback_answer_permitted: boolean, scm_mutation_permitted: boolean, raw_provider_material_retained: boolean, raw_callback_material_retained: boolean, next_action: string, };
