// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexCallbackDiagnosticDto } from "./CodexCallbackDiagnosticDto";

/**
 * Client-safe diagnostics for Codex callback response outcomes.
 */
export type CodexCallbackDiagnosticsDto = { outcomes: Array<CodexCallbackDiagnosticDto>, client_can_answer_callbacks: boolean, client_can_cancel_provider: boolean, client_can_recover_sessions: boolean, client_can_mutate_tasks: boolean, source_status: string, source_summary: string | null, };
