// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexDecodeOutcomeDiagnosticDto } from "./CodexDecodeOutcomeDiagnosticDto";
import type { CodexStdioFrameIngestionDiagnosticDto } from "./CodexStdioFrameIngestionDiagnosticDto";
import type { CodexTransportExecutionDiagnosticDto } from "./CodexTransportExecutionDiagnosticDto";
import type { CodexTransportExecutorAuthorityDiagnosticDto } from "./CodexTransportExecutorAuthorityDiagnosticDto";
import type { CodexTransportExecutorEnvelopeDiagnosticDto } from "./CodexTransportExecutorEnvelopeDiagnosticDto";
import type { CodexTransportReceiptDiagnosticDto } from "./CodexTransportReceiptDiagnosticDto";
import type { CodexTransportSessionDiagnosticDto } from "./CodexTransportSessionDiagnosticDto";

/**
 * Client-safe diagnostics for Codex transport executor handoff state.
 */
export type CodexTransportExecutorDiagnosticsDto = { sessions: Array<CodexTransportSessionDiagnosticDto>, authorities: Array<CodexTransportExecutorAuthorityDiagnosticDto>, envelopes: Array<CodexTransportExecutorEnvelopeDiagnosticDto>, executions: Array<CodexTransportExecutionDiagnosticDto>, frames: Array<CodexStdioFrameIngestionDiagnosticDto>, decode_outcomes: Array<CodexDecodeOutcomeDiagnosticDto>, transport_receipts: Array<CodexTransportReceiptDiagnosticDto>, session_count: number, frame_count: number, decode_outcome_count: number, receipt_count: number, repair_required_count: number, client_can_execute_provider_write: boolean, client_can_answer_callbacks: boolean, client_can_cancel_provider: boolean, client_can_mutate_tasks: boolean, provider_material_exposed: boolean, raw_streams_exposed: boolean, source_status: string, source_summary: string | null, };
