// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexTransportExecutorEnvelopeDiagnosticDto = { envelope_id: string, request_id: string, send_command_id: string, write_attempt_id: string, status: string, blockers: Array<string>, receipt_id: string, event_id: string, evidence_refs: Array<string>, raw_payload_retained: boolean, raw_stream_retained: boolean, task_mutation_permitted: boolean, next_action: string, };
