// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexIngestionObservationDiagnosticDto } from "./CodexIngestionObservationDiagnosticDto";

/**
 * Client-safe diagnostics for Codex ingestion acceptance.
 */
export type CodexIngestionDiagnosticsDto = { observations: Array<CodexIngestionObservationDiagnosticDto>, client_can_mutate_observations: boolean, provider_execution_available: boolean, source_status: string, source_summary: string | null, };
