// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexStdioFrameIngestionDiagnosticDto = { ingestion_id: string, frame_source_id: string, runtime_instance_id: string, sequence: number, decode_status: string, receipt_id: string, observation_event_id: string | null, evidence_refs: Array<string>, raw_payload_retained: boolean, raw_stream_retained: boolean, task_mutation_permitted: boolean, next_action: string, };
