// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexRecoveryExecutionAttemptDiagnosticDto } from "./CodexRecoveryExecutionAttemptDiagnosticDto";

/**
 * Client-safe diagnostics for Codex provider recovery execution state.
 */
export type CodexRecoveryExecutionDiagnosticsDto = { attempts: Array<CodexRecoveryExecutionAttemptDiagnosticDto>, client_can_execute_provider_write: boolean, client_can_resume_provider: boolean, client_can_promote_replacement_thread: boolean, client_can_interrupt_provider: boolean, client_can_answer_callbacks: boolean, client_can_mutate_tasks: boolean, client_can_accept_review: boolean, client_can_mutate_scm: boolean, provider_material_exposed: boolean, source_status: string, source_summary: string | null, };
