// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One callback response execution attempt visible to diagnostics clients.
 */
export type CodexCallbackResponseExecutionAttemptDiagnosticDto = { request_id: string, callback_response_id: string, envelope_id: string, provider_callback_id: string, task_id: string, work_item_id: string, admission_id: string | null, policy_id: string | null, live_executor_outcome_id: string | null, runtime_receipt_id: string | null, provider_instance_id: string, callback_response_write_attempt_id: string | null, status: string, blockers: Array<string>, runtime_progress: string | null, callback_refs: Array<string>, evidence_refs: Array<string>, provider_completion_recorded: boolean, provider_write_recorded: boolean, task_completion_permitted: boolean, review_acceptance_permitted: boolean, callback_answer_permitted: boolean, cancellation_permitted: boolean, resume_permitted: boolean, scm_mutation_permitted: boolean, raw_callback_material_retained: boolean, next_action: string, };
