// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexTurnStartDiagnosticDto } from "./CodexTurnStartDiagnosticDto";

/**
 * Client-safe diagnostics for Codex turn-start outcomes.
 */
export type CodexTurnStartDiagnosticsDto = { outcomes: Array<CodexTurnStartDiagnosticDto>, client_can_start_turns: boolean, client_can_answer_callbacks: boolean, client_can_mutate_tasks: boolean, source_status: string, source_summary: string | null, };
