// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexTransportExecutorAuthorityDiagnosticDto = { authority_id: string, provider_instance_id: string, preflight_id: string, write_attempt_id: string, status: string, blockers: Array<string>, evidence_refs: Array<string>, task_mutation_permitted: boolean, next_action: string, };
