// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexTurnStartDiagnosticDto = { request_id: string, admission_id: string | null, envelope_id: string | null, status: string, receipt_id: string, evidence_refs: Array<string>, raw_payload_retained: boolean, task_mutation_permitted: boolean, next_action: string, summary: string, };
