// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexStdioWriteDiagnosticDto } from "./CodexStdioWriteDiagnosticDto";
import type { CodexSubscriptionDiagnosticDto } from "./CodexSubscriptionDiagnosticDto";

/**
 * Client-safe diagnostics for Codex send/subscription state.
 */
export type CodexSubscriptionDiagnosticsDto = { writes: Array<CodexStdioWriteDiagnosticDto>, subscriptions: Array<CodexSubscriptionDiagnosticDto>, client_can_write_provider: boolean, client_can_answer_callbacks: boolean, client_can_cancel_provider: boolean, client_can_mutate_tasks: boolean, source_status: string, source_summary: string | null, };
