// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One live executor attempt visible to diagnostics clients.
 */
export type CodexLiveExecutorAttemptDiagnosticDto = { outcome_id: string, provider_instance_id: string, write_attempt_id: string, receipt_refs: Array<string>, thread_id: string | null, turn_id: string | null, final_turn_status: string | null, status: string, method_sequence: Array<string>, notification_count: number, server_request_count: number, cleanup_status: string, evidence_refs: Array<string>, provider_write_executed: boolean, task_mutation_permitted: boolean, callback_response_permitted: boolean, cancellation_permitted: boolean, resume_permitted: boolean, next_action: string, };
