// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexLiveSpawnSmokeDiagnosticDto } from "./CodexLiveSpawnSmokeDiagnosticDto";

/**
 * Client-safe diagnostics for Codex live spawn smoke attempts.
 */
export type CodexLiveSpawnSmokeDiagnosticsDto = { smoke_attempts: Array<CodexLiveSpawnSmokeDiagnosticDto>, client_can_start_smoke: boolean, client_can_mutate_tasks: boolean, provider_turns_available: boolean, source_status: string, source_summary: string | null, };
