// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionScmProviderNeutralReadinessStatus } from "./CompletionScmProviderNeutralReadinessStatus";

export type CompletionScmReadinessDto = { readiness_id: string, candidate_id: string, task_id: string, work_item_id: string, completion_id: string, operator_ref: string, evidence_refs: Array<string>, status: CompletionScmProviderNeutralReadinessStatus, };
