// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionScmReadinessDto } from "./CompletionScmReadinessDto";

export type CompletionScmControlDto = { dto_id: string, read_model_id: string, source_history_available: boolean, adapter_label: string, workflow_label: string, candidate_count: number, readiness_count: number, ready_count: number, unsupported_count: number, repair_required_count: number, blocker_count: number, repair_required: boolean, readiness: Array<CompletionScmReadinessDto>, scm_authority_granted: boolean, forge_authority_granted: boolean, provider_authority_granted: boolean, raw_material_exposed: boolean, };
