// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskCommandAdmissionDto } from "./ControlSelectedTaskCommandAdmissionDto";
import type { ControlSelectedTaskReviewOutcomeRouteNoEffectsDto } from "./ControlSelectedTaskReviewOutcomeRouteNoEffectsDto";
import type { ControlSelectedTaskRouteAdmissionRefusalDto } from "./ControlSelectedTaskRouteAdmissionRefusalDto";

export type ControlSelectedTaskCompletionRouteAdmissionDto = { admission_id: string, project_id: string, task_id: string, route_id: string, route_candidate: string, decision_ref: string | null, status: string, command_admission: ControlSelectedTaskCommandAdmissionDto | null, refusal: ControlSelectedTaskRouteAdmissionRefusalDto | null, evidence_refs: Array<string>, no_effects: ControlSelectedTaskReviewOutcomeRouteNoEffectsDto, };
