// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlProductWorkflowLaneDto = { lane: string, count: number, task_refs: Array<string>, rationale_refs: Array<string>, };
