// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskReviewOutcomeRouteNoEffectsDto } from "./ControlSelectedTaskReviewOutcomeRouteNoEffectsDto";
import type { ControlSelectedTaskReviewOutcomeRouteSourceCountsDto } from "./ControlSelectedTaskReviewOutcomeRouteSourceCountsDto";

export type ControlSelectedTaskReviewOutcomeRouteDto = { route_id: string, project_id: string, task_id: string, status: string, primary_route: string, candidates: Array<string>, decision_ref: string | null, decision_outcome: string | null, work_item_refs: Array<string>, evidence_refs: Array<string>, downstream_command_hints: Array<string>, blockers: Array<string>, source_counts: ControlSelectedTaskReviewOutcomeRouteSourceCountsDto, no_effects: ControlSelectedTaskReviewOutcomeRouteNoEffectsDto, };
