// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlProviderReadIntentProjectionDto } from "./ControlProviderReadIntentProjectionDto";
import type { ControlProviderReadIntentSourceCountsDto } from "./ControlProviderReadIntentSourceCountsDto";

/**
 * Serializable provider read-intent query result.
 */
export type ControlProviderReadIntentQueryResultDto = { query_id: string, projection: ControlProviderReadIntentProjectionDto, source_counts: ControlProviderReadIntentSourceCountsDto, credential_resolution_performed: boolean, provider_network_call_performed: boolean, provider_effect_executed: boolean, callback_effect_executed: boolean, interruption_effect_executed: boolean, recovery_effect_executed: boolean, task_mutation_executed: boolean, raw_provider_payload_retained: boolean, };
