// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskProductReworkDto = { status: string | null, summary: string | null, refusal_reason: string | null, reviewed_work_item_refs: Array<string>, reviewed_evidence_refs: Array<string>, };
