// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable project authority-domain publication.
 */
export type ControlProjectAuthorityDomainDto = { domain: string, state: string, authoritative_host_id: string | null, fallback_host_ids: Array<string>, mutation_allowed: boolean | null, reason: string | null, note: string | null, };
