// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlPlanningSessionOutputRefsDto = { artifact_refs: Array<string>, task_seed_refs: Array<string>, memory_proposal_refs: Array<string>, research_run_brief_refs: Array<string>, };
