// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskScmHandoffNoEffectsDto = { scm_mutation_performed: boolean, forge_mutation_performed: boolean, credential_resolution_performed: boolean, task_mutation_performed: boolean, provider_execution_performed: boolean, review_mutation_performed: boolean, accepted_memory_apply_performed: boolean, planning_apply_performed: boolean, projection_write_performed: boolean, ui_effect_performed: boolean, };
