// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskReviewOutcomeRouteSourceCountsDto = { decision_records: number, work_item_refs: number, evidence_refs: number, review_gap_count: number, scm_handoff_refs: number, downstream_command_hints: number, blockers: number, };
