// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskReviewEvidenceDto } from "./ControlSelectedTaskReviewEvidenceDto";
import type { ControlSelectedTaskReviewGapDto } from "./ControlSelectedTaskReviewGapDto";
import type { ControlSelectedTaskReviewNextNoEffectsDto } from "./ControlSelectedTaskReviewNextNoEffectsDto";
import type { ControlSelectedTaskReviewNextSourceCountsDto } from "./ControlSelectedTaskReviewNextSourceCountsDto";
import type { ControlSelectedTaskReviewNextStepDto } from "./ControlSelectedTaskReviewNextStepDto";
import type { ControlSelectedTaskReviewSummaryDto } from "./ControlSelectedTaskReviewSummaryDto";

export type ControlSelectedTaskReviewNextDto = { review_next_id: string, project_id: string, task_id: string, review: ControlSelectedTaskReviewSummaryDto, evidence: ControlSelectedTaskReviewEvidenceDto, next: ControlSelectedTaskReviewNextStepDto, source_counts: ControlSelectedTaskReviewNextSourceCountsDto, gaps: Array<ControlSelectedTaskReviewGapDto>, no_effects: ControlSelectedTaskReviewNextNoEffectsDto, };
