// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlPlanningSessionOutputRefsDto } from "./ControlPlanningSessionOutputRefsDto";
import type { ControlPlanningSessionSourceKindCountDto } from "./ControlPlanningSessionSourceKindCountDto";

export type ControlPlanningSessionSummaryDto = { session_id: string, kind: string, status: string, prompt_or_template_refs: Array<string>, participant_count: number, source_ref_count: number, source_kind_counts: Array<ControlPlanningSessionSourceKindCountDto>, output_refs: ControlPlanningSessionOutputRefsDto, };
