// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlOrchestrationRunReviewPatchDto = { run_id: string, file_ref: string, available: boolean, unreachable_reason: string | null, patch: string | null, additions: bigint, deletions: bigint, truncated: boolean, };
