// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlAcceptedMemoryProjectionWriteCountsDto } from "./ControlAcceptedMemoryProjectionWriteCountsDto";
import type { ControlAcceptedMemoryProjectionWriteEntryDto } from "./ControlAcceptedMemoryProjectionWriteEntryDto";

export type ControlAcceptedMemoryProjectionWriteDiagnosticsDto = { project_id: string, entries: Array<ControlAcceptedMemoryProjectionWriteEntryDto>, counts: ControlAcceptedMemoryProjectionWriteCountsDto, projection_write_performed: boolean, scm_effect_performed: boolean, import_or_apply_performed: boolean, embedding_available: boolean, provider_sync_available: boolean, task_mutation_performed: boolean, ui_effect_performed: boolean, };
