// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskCommandAdmissionCommandDto } from "./ControlSelectedTaskCommandAdmissionCommandDto";
import type { ControlSelectedTaskCommandAdmissionDto } from "./ControlSelectedTaskCommandAdmissionDto";
import type { ControlSelectedTaskCompletionRouteApplyRefusalDto } from "./ControlSelectedTaskCompletionRouteApplyRefusalDto";
import type { ControlSelectedTaskReviewOutcomeRouteNoEffectsDto } from "./ControlSelectedTaskReviewOutcomeRouteNoEffectsDto";

export type ControlSelectedTaskCompletionRouteApplyDto = { apply_id: string, project_id: string, task_id: string, route_admission_id: string, route_id: string, review_decision_ref: string | null, status: string, command: ControlSelectedTaskCommandAdmissionCommandDto | null, command_admission: ControlSelectedTaskCommandAdmissionDto | null, refusal: ControlSelectedTaskCompletionRouteApplyRefusalDto | null, evidence_refs: Array<string>, operator_ref: string, no_effects: ControlSelectedTaskReviewOutcomeRouteNoEffectsDto, };
