// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskReviewDecisionCommandDto = { decision_id: string, project_id: string, task_id: string, action: string, outcome: string, expected_revision: string, operator_ref: string, reviewed_evidence_refs: Array<string>, idempotency_key: string, reason: string | null, };
