// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskCompletionRouteAdmissionDto } from "./ControlSelectedTaskCompletionRouteAdmissionDto";
import type { ControlSelectedTaskReviewOutcomeRouteNoEffectsDto } from "./ControlSelectedTaskReviewOutcomeRouteNoEffectsDto";
import type { ControlSelectedTaskReworkDelegationRouteAdmissionDto } from "./ControlSelectedTaskReworkDelegationRouteAdmissionDto";

export type ControlSelectedTaskRouteAdmissionDto = { admission_id: string, project_id: string, task_id: string, route_id: string, completion: ControlSelectedTaskCompletionRouteAdmissionDto, rework_delegation: ControlSelectedTaskReworkDelegationRouteAdmissionDto, no_effects: ControlSelectedTaskReviewOutcomeRouteNoEffectsDto, };
