// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskProductBlockerDto = { family: string, reason: string, evidence_refs: Array<string>, };
