// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlAcceptedMemorySourceCountsDto = { accepted_records: number, out_of_scope_accepted_records: number, skipped_records: number, skipped_proposal_records: number, skipped_unsupported_records: number, skipped_decode_errors: number, source_refs: number, link_refs: number, evidence_refs: number, supersession_refs: number, };
