// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskOperatorTaskCommandCandidateDto = { action: string, task_id: string, expected_revision: string | null, };
