// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable authority-map validation issue.
 */
export type ControlProjectAuthorityIssueDto = { kind: string, domain: string | null, host_id: string | null, reason: string | null, };
