// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlDelegationActionDto } from "./ControlDelegationActionDto";

export type ControlOrchestratorDesignationDto = { designation_id: string, project_id: string, orchestrator_provider_instance: string, allowed_worker_provider_instances: Array<string> | null, allowed_worker_models: Array<string> | null, concurrent_run_budget: bigint, per_run_token_budget: bigint | null, per_run_time_budget_seconds: bigint | null, allowed_actions: Array<ControlDelegationActionDto>, steering_permitted: boolean, status: string, revision_id: string, created_at: bigint, updated_at: bigint, };
