// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable provider read-intent source counts.
 */
export type ControlProviderReadIntentSourceCountsDto = { credential_status_records: number, repository_metadata_records: number, pull_request_records: number, status_check_records: number, };
