// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskProductCompletionDto = { status: string | null, command_available: boolean, refusal_reason: string | null, evidence_refs: Array<string>, };
