// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskProductSourceStatusDto } from "./ControlSelectedTaskProductSourceStatusDto";

export type ControlSelectedTaskProductSourceHealthDto = { sources: Array<ControlSelectedTaskProductSourceStatusDto>, missing_count: number, partial_count: number, };
