// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskOperatorTaskCommandCandidateDto } from "./ControlSelectedTaskOperatorTaskCommandCandidateDto";

export type ControlSelectedTaskOperatorActionCandidateDto = { family: string, readiness_status: string, disposition: string, task_command: ControlSelectedTaskOperatorTaskCommandCandidateDto | null, label: string, reason: string, evidence_refs: Array<string>, blocker_refs: Array<string>, expected_revision_required: boolean, reason_required: boolean, };
