// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlTaskSeedPromotionDiagnosticEntryDto } from "./ControlTaskSeedPromotionDiagnosticEntryDto";

export type ControlTaskSeedPromotionDiagnosticsDto = { project_id: string, task_seed_records: number, ready_count: number, blocked_count: number, rejected_count: number, promoted_count: number, duplicate_promoted_task_ref_count: number, missing_promoted_task_ref_count: number, entries: Array<ControlTaskSeedPromotionDiagnosticEntryDto>, client_can_mutate: boolean, task_creation_performed: boolean, provider_execution_performed: boolean, raw_planning_body_exposed: boolean, };
