// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable sanitized diff summary record.
 */
export type ControlDiffSummaryRecordDto = { diff_id: string, kind: string, source_boundary_ref: string, target_boundary_ref: string, source_ref: string | null, adapter_ref: string | null, generated_by_ref: string, confidence: string, summary: string, changed_paths: Array<string>, evidence_refs: Array<string>, artifact_refs: Array<string>, };
