// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlForgePullRequestTextSourceDto = "operator_provided" | "agent_suggested" | "generated_from_evidence";
