// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlAcceptedMemoryReviewReceiptStorageCountsDto } from "./ControlAcceptedMemoryReviewReceiptStorageCountsDto";
import type { ControlAcceptedMemoryReviewReceiptStorageRecordDto } from "./ControlAcceptedMemoryReviewReceiptStorageRecordDto";

export type ControlAcceptedMemoryReviewReceiptStorageDiagnosticsDto = { diagnostics_id: string, project_id: string, receipts: Array<ControlAcceptedMemoryReviewReceiptStorageRecordDto>, counts: ControlAcceptedMemoryReviewReceiptStorageCountsDto, review_receipts_persisted: boolean, active_memory_apply_performed: boolean, projection_write_performed: boolean, scm_effect_performed: boolean, embedding_available: boolean, provider_sync_available: boolean, automatic_extraction_performed: boolean, task_mutation_performed: boolean, agent_scheduling_performed: boolean, ui_effect_performed: boolean, };
