// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlTaskWorkflowGuidanceDto = { source: string, safe_action: string, reason: string, evidence_refs: Array<string>, missing_evidence_areas: Array<string>, blocked_reason: string | null, };
