// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskReviewNextSourceCountsDto = { task_records: number, work_items: number, active_work_items: number, completed_work_items: number, reviewable_work_items: number, receipt_refs: number, checkpoint_refs: number, diff_summary_refs: number, validation_refs: number, timeline_refs: number, review_refs: number, task_completion_refs: number, guidance_refs: number, gap_count: number, };
