// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlResearchRunBriefSummaryDto = { run_id: string, status: string, source_plan_ref_count: number, question_count: number, source_ref_count: number, observation_ref_count: number, synthesis_ref_count: number, promotion_target_ref_count: number, coverage_ref_count: number, gap_ref_count: number, };
