// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable state record DTO.
 */
export type ControlStateRecordDto = { id: string, domain: string, kind: string, revision_id: string, media_type: string | null, payload_bytes: Array<number>, };
