// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskOperatorActionBlockerDto } from "./ControlSelectedTaskOperatorActionBlockerDto";
import type { ControlSelectedTaskOperatorActionCandidateDto } from "./ControlSelectedTaskOperatorActionCandidateDto";
import type { ControlSelectedTaskOperatorActionGateSourceCountsDto } from "./ControlSelectedTaskOperatorActionGateSourceCountsDto";
import type { ControlSelectedTaskOperatorActionNoEffectsDto } from "./ControlSelectedTaskOperatorActionNoEffectsDto";

export type ControlSelectedTaskOperatorActionGateDto = { gate_id: string, project_id: string, task_id: string, expected_revision: string | null, actor_ref: string | null, candidates: Array<ControlSelectedTaskOperatorActionCandidateDto>, source_counts: ControlSelectedTaskOperatorActionGateSourceCountsDto, blockers: Array<ControlSelectedTaskOperatorActionBlockerDto>, no_effects: ControlSelectedTaskOperatorActionNoEffectsDto, };
