// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlAcceptedMemorySummaryDto = { memory_id: string, source_proposal_id: string | null, scope: string, kind: string, status: string, sensitivity: string, retention: string, confidence: string, created_by_ref: string, accepted_by_ref: string, reviewer_ref: string, source_ref_count: number, link_ref_count: number, evidence_ref_count: number, supersedes_count: number, superseded_by_count: number, };
