// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlAcceptedMemoryProjectionImportAdmissionDto } from "./ControlAcceptedMemoryProjectionImportAdmissionDto";
import type { ControlAcceptedMemoryProjectionImportCandidateDto } from "./ControlAcceptedMemoryProjectionImportCandidateDto";
import type { ControlAcceptedMemoryProjectionImportConflictDto } from "./ControlAcceptedMemoryProjectionImportConflictDto";
import type { ControlAcceptedMemoryProjectionImportCountsDto } from "./ControlAcceptedMemoryProjectionImportCountsDto";

export type ControlAcceptedMemoryProjectionImportDiagnosticsDto = { project_id: string, candidates: Array<ControlAcceptedMemoryProjectionImportCandidateDto>, admissions: Array<ControlAcceptedMemoryProjectionImportAdmissionDto>, conflicts: Array<ControlAcceptedMemoryProjectionImportConflictDto>, counts: ControlAcceptedMemoryProjectionImportCountsDto, projected_file_read_performed: boolean, active_memory_apply_performed: boolean, scm_effect_performed: boolean, embedding_available: boolean, provider_sync_available: boolean, task_mutation_performed: boolean, ui_effect_performed: boolean, };
