// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlProjectResourceActionDto = "attach" | "update" | "repair" | "remove" | "set_management_projection" | "clear_management_projection";
