// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlProviderReadIntentEntryDto } from "./ControlProviderReadIntentEntryDto";

/**
 * Serializable provider read-intent projection.
 */
export type ControlProviderReadIntentProjectionDto = { projection_id: string, total_count: number, credential_status_count: number, repository_metadata_count: number, pull_request_count: number, status_check_count: number, ready_count: number, duplicate_noop_count: number, blocked_count: number, repair_required_count: number, blocker_count: number, evidence_ref_count: number, entries: Array<ControlProviderReadIntentEntryDto>, credential_resolution_performed: boolean, provider_network_call_performed: boolean, provider_effect_executed: boolean, callback_effect_executed: boolean, interruption_effect_executed: boolean, recovery_effect_executed: boolean, task_mutation_executed: boolean, raw_provider_payload_retained: boolean, };
