// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlTaskSeedPromotionDiagnosticEntryDto = { seed_id: string, project_id: string, readiness: string, review_state: string, promotion_state: string, promoted_task_ref: string | null, promoted_task_exists: boolean, duplicate_promoted_task_ref: boolean, blocking_question_count: number, };
