// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlForgePullRequestProviderDto } from "./ControlForgePullRequestProviderDto";
import type { ControlForgePullRequestTextSourceDto } from "./ControlForgePullRequestTextSourceDto";

/**
 * Operator-confirmed PR-creation scope on the run delivery command DTO.
 * Mirrors the durable `ForgePullRequestCreationScope`: forge provider, base
 * and head refs, and title/body sources only — raw PR title/body text never
 * crosses the command boundary.
 */
export type ControlForgePullRequestCreationScopeDto = { forge_provider: ControlForgePullRequestProviderDto, base_branch: string, head_branch: string, title_source: ControlForgePullRequestTextSourceDto, body_source: ControlForgePullRequestTextSourceDto, };
