// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskProductCommandPreviewDto } from "./ControlSelectedTaskProductCommandPreviewDto";

export type ControlSelectedTaskProductCommandPreviewsDto = { admitted_count: number, refused_count: number, previews: Array<ControlSelectedTaskProductCommandPreviewDto>, };
