// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexProviderDiagnosticsDto } from "./CodexProviderDiagnosticsDto";
import type { CompletionScmCaptureControlDto } from "./CompletionScmCaptureControlDto";
import type { CompletionScmCapturePreparationControlDto } from "./CompletionScmCapturePreparationControlDto";
import type { CompletionScmControlDto } from "./CompletionScmControlDto";
import type { EffigyDiagnosticsDto } from "./EffigyDiagnosticsDto";
import type { GitDryRunExecutionControlDto } from "./GitDryRunExecutionControlDto";
import type { LiveEvidenceCompletionControlDto } from "./LiveEvidenceCompletionControlDto";
import type { ScmCaptureDryRunControlDto } from "./ScmCaptureDryRunControlDto";
import type { ScmCaptureDryRunExecutionControlDto } from "./ScmCaptureDryRunExecutionControlDto";
import type { ScmCaptureReviewControlDto } from "./ScmCaptureReviewControlDto";
import type { ScmCaptureReviewDecisionControlDto } from "./ScmCaptureReviewDecisionControlDto";
import type { ScmCaptureWorkflowControlDto } from "./ScmCaptureWorkflowControlDto";
import type { ScmChangeRequestPrepControlDto } from "./ScmChangeRequestPrepControlDto";
import type { ScmSessionDiagnosticsDto } from "./ScmSessionDiagnosticsDto";
import type { StewardDiagnosticsDto } from "./StewardDiagnosticsDto";
import type { SyncDiagnosticsDto } from "./SyncDiagnosticsDto";
import type { TaskAgentDiagnosticsDto } from "./TaskAgentDiagnosticsDto";

/**
 * Serializable combined diagnostics snapshot.
 */
export type ControlDiagnosticsSnapshotDto = { steward: StewardDiagnosticsDto, effigy: EffigyDiagnosticsDto, management_sync: SyncDiagnosticsDto, scm_session: ScmSessionDiagnosticsDto, task_agent: TaskAgentDiagnosticsDto, codex_provider: CodexProviderDiagnosticsDto, live_evidence_completion: LiveEvidenceCompletionControlDto, completion_scm_readiness: CompletionScmControlDto, completion_scm_capture: CompletionScmCaptureControlDto, completion_scm_capture_preparation: CompletionScmCapturePreparationControlDto, scm_capture_dry_run: ScmCaptureDryRunControlDto, scm_capture_dry_run_execution: ScmCaptureDryRunExecutionControlDto, git_dry_run_execution: GitDryRunExecutionControlDto, scm_capture_workflow: ScmCaptureWorkflowControlDto, scm_capture_review: ScmCaptureReviewControlDto, scm_capture_review_decision: ScmCaptureReviewDecisionControlDto, scm_change_request_preparation: ScmChangeRequestPrepControlDto, };
