// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlTaskWorkflowRuntimeDto = { runtime_receipt_refs: Array<string>, command_evidence_refs: Array<string>, task_completion_refs: Array<string>, };
