// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskCommandAdmissionCandidateDto } from "./ControlSelectedTaskCommandAdmissionCandidateDto";
import type { ControlSelectedTaskCommandAdmissionCommandDto } from "./ControlSelectedTaskCommandAdmissionCommandDto";
import type { ControlSelectedTaskCommandAdmissionNoEffectsDto } from "./ControlSelectedTaskCommandAdmissionNoEffectsDto";
import type { ControlSelectedTaskCommandAdmissionRefusalDto } from "./ControlSelectedTaskCommandAdmissionRefusalDto";

export type ControlSelectedTaskCommandAdmissionDto = { admission_id: string, project_id: string, task_id: string, family: string, status: string, command: ControlSelectedTaskCommandAdmissionCommandDto | null, candidate: ControlSelectedTaskCommandAdmissionCandidateDto | null, refusal: ControlSelectedTaskCommandAdmissionRefusalDto | null, operator_ref: string, evidence_refs: Array<string>, no_effects: ControlSelectedTaskCommandAdmissionNoEffectsDto, };
