// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlResponseBodyDto } from "./ControlResponseBodyDto";
import type { ControlResponseStatusDto } from "./ControlResponseStatusDto";

/**
 * Serializable response envelope for the first control API wire format.
 */
export type ControlResponseEnvelopeDto = { protocol_family: string, protocol_version: number, request_id: string, status: ControlResponseStatusDto, body: ControlResponseBodyDto, };
