// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable task acceptance criterion for authoring commands.
 */
export type ControlTaskAcceptanceCriterionDto = { text: string, required: boolean, };
