// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlProjectAuthorityDomainDto } from "./ControlProjectAuthorityDomainDto";
import type { ControlProjectAuthorityIssueDto } from "./ControlProjectAuthorityIssueDto";

/**
 * Serializable project authority-map publication.
 */
export type ControlProjectAuthorityMapDto = { project_id: string, domains: Array<ControlProjectAuthorityDomainDto>, issues: Array<ControlProjectAuthorityIssueDto>, };
