// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlMemoryProposalReviewDiagnosticEntryDto = { proposal_id: string, scope_ref: string, proposal_status: string, review_status: string, reviewer_ref_present: boolean, note_present: boolean, source_ref_count: number, link_ref_count: number, };
