// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlAcceptedMemoryActiveApplyCountsDto = { source_records: number, admitted: number, duplicate_noops: number, blocked: number, blockers: number, missing_ref_blockers: number, review_state_blockers: number, stale_ref_blockers: number, raw_payload_blockers: number, effect_blockers: number, unsupported_records_skipped: number, other_project_records_skipped: number, decode_failed_records: number, };
