// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlMemoryProposalSummaryDto = { proposal_id: string, display_title: string | null, display_summary: string | null, display_redacted: boolean, display_truncated: boolean, scope: string, kind: string, status: string, review_status: string, sensitivity: string, retention: string, source_ref_count: number, link_ref_count: number, supersedes_count: number, superseded_by_count: number, };
