// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskRouteAdmissionPreviewDto = { family: string, summary: string, source_refs: Array<string>, evidence_refs: Array<string>, };
