// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskScmHandoffNextStepDto = { category: string, summary: string, next_ref: string | null, rationale_refs: Array<string>, };
