// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlAcceptedMemoryProjectionImportBlockerDto } from "./ControlAcceptedMemoryProjectionImportBlockerDto";
import type { ControlAcceptedMemoryProjectionImportSummaryDto } from "./ControlAcceptedMemoryProjectionImportSummaryDto";

export type ControlAcceptedMemoryProjectionImportConflictDto = { conflict_ref: string, admission_ref: string, candidate_ref: string, memory_id: string | null, file_ref: string, status: string, summary: ControlAcceptedMemoryProjectionImportSummaryDto | null, blockers: Array<ControlAcceptedMemoryProjectionImportBlockerDto>, };
