// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlProductWorkflowContextDto } from "./ControlProductWorkflowContextDto";
import type { ControlProductWorkflowGapDto } from "./ControlProductWorkflowGapDto";
import type { ControlProductWorkflowLaneDto } from "./ControlProductWorkflowLaneDto";
import type { ControlProductWorkflowNextDto } from "./ControlProductWorkflowNextDto";
import type { ControlProductWorkflowNoEffectsDto } from "./ControlProductWorkflowNoEffectsDto";
import type { ControlProductWorkflowPlanningContextDto } from "./ControlProductWorkflowPlanningContextDto";
import type { ControlProductWorkflowProjectDto } from "./ControlProductWorkflowProjectDto";
import type { ControlProductWorkflowReviewDto } from "./ControlProductWorkflowReviewDto";
import type { ControlProductWorkflowRuntimeDto } from "./ControlProductWorkflowRuntimeDto";
import type { ControlProductWorkflowScmReadinessDto } from "./ControlProductWorkflowScmReadinessDto";
import type { ControlProductWorkflowSourceCountsDto } from "./ControlProductWorkflowSourceCountsDto";

export type ControlProductWorkflowSummaryDto = { summary_id: string, project_id: string, project: ControlProductWorkflowProjectDto, task_lanes: Array<ControlProductWorkflowLaneDto>, planning_context: ControlProductWorkflowPlanningContextDto, context: ControlProductWorkflowContextDto, runtime: ControlProductWorkflowRuntimeDto, review: ControlProductWorkflowReviewDto, scm_readiness: ControlProductWorkflowScmReadinessDto, next: ControlProductWorkflowNextDto, source_counts: ControlProductWorkflowSourceCountsDto, gaps: Array<ControlProductWorkflowGapDto>, no_effects: ControlProductWorkflowNoEffectsDto, };
