// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlTaskWorkflowTaskDto = { title: string, activity: string, assignment: string, action_type: string, };
