// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlProductWorkflowContextDto = { memory_proposal_refs: Array<string>, accepted_memory_refs: Array<string>, research_run_refs: Array<string>, };
