// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlProductWorkflowProjectDto = { display_name: string | null, status: string | null, authority_refs: Array<string>, };
