// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported memory proposal review command actions.
 */
export type ControlMemoryProposalReviewActionDto = "queue" | "defer" | "reject" | "mark_reviewed_for_promotion";
