// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSelectedTaskReviewOutcomeRouteNoEffectsDto } from "./ControlSelectedTaskReviewOutcomeRouteNoEffectsDto";
import type { ControlSelectedTaskRouteAdmissionPreviewDto } from "./ControlSelectedTaskRouteAdmissionPreviewDto";
import type { ControlSelectedTaskRouteAdmissionRefusalDto } from "./ControlSelectedTaskRouteAdmissionRefusalDto";

export type ControlSelectedTaskReworkDelegationRouteAdmissionDto = { admission_id: string, project_id: string, task_id: string, route_id: string, route_candidate: string, decision_ref: string | null, status: string, rework_preview: ControlSelectedTaskRouteAdmissionPreviewDto | null, delegation_preview: ControlSelectedTaskRouteAdmissionPreviewDto | null, refusal: ControlSelectedTaskRouteAdmissionRefusalDto | null, work_item_refs: Array<string>, evidence_refs: Array<string>, no_effects: ControlSelectedTaskReviewOutcomeRouteNoEffectsDto, };
