// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlOrchestrationRunCloseoutDto } from "./ControlOrchestrationRunCloseoutDto";
import type { ControlOrchestrationRunDiffOverviewDto } from "./ControlOrchestrationRunDiffOverviewDto";
import type { ControlOrchestrationRunTransitionDto } from "./ControlOrchestrationRunTransitionDto";
import type { ControlOrchestrationRunValidationDto } from "./ControlOrchestrationRunValidationDto";

/**
 * Delivery-review read model for one run (closeout + validation + diff).
 */
export type ControlOrchestrationRunReviewDto = { project_id: string, run_id: string, state: string, objective_scope: string, acceptance: Array<string>, stop_conditions: Array<string>, provider_instance: string, provider_model: string, orchestrator_designation: string | null, worktree_ref: string | null, base_ref: string | null, conversation_id: string | null, closeout: ControlOrchestrationRunCloseoutDto | null, transitions: Array<ControlOrchestrationRunTransitionDto>, created_at: bigint, updated_at: bigint, validation: ControlOrchestrationRunValidationDto, diff: ControlOrchestrationRunDiffOverviewDto, };
