// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlOrchestrationRunDiffFileDto } from "./ControlOrchestrationRunDiffFileDto";

export type ControlOrchestrationRunDiffOverviewDto = { base_ref: string | null, available: boolean, unreachable_reason: string | null, files: Array<ControlOrchestrationRunDiffFileDto>, truncated: boolean, };
