// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable provider read-intent entry summary.
 */
export type ControlProviderReadIntentEntryDto = { intent_id: string, source_persisted_refresh_id: string, family: string, status: string, provider_context_ref: string | null, provider_instance_ref: string | null, forge_provider: string | null, remote_repo_ref: string | null, operation_family: string, blocker_count: number, evidence_ref_count: number, duplicate_refresh_detected: boolean, stopped_refresh_recorded: boolean, credential_resolution_performed: boolean, provider_network_call_performed: boolean, provider_effect_executed: boolean, callback_effect_executed: boolean, interruption_effect_executed: boolean, recovery_effect_executed: boolean, task_mutation_executed: boolean, raw_provider_payload_retained: boolean, };
