// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlCommandDto } from "./ControlCommandDto";
import type { ControlQueryDto } from "./ControlQueryDto";

/**
 * Serializable request body.
 */
export type ControlRequestBodyDto = { "type": "query", query: ControlQueryDto, } | { "type": "command", command: ControlCommandDto, };
