// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlResearchRunBriefSourceCountsDto = { run_records: number, source_plan_refs: number, questions: number, source_refs: number, observation_refs: number, synthesis_refs: number, promotion_target_refs: number, coverage_refs: number, gap_refs: number, };
