// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Delegation actions a designation envelope may grant (contract 033
 * Delegation Action Rule). `message_run` is lane phase 4.
 */
export type ControlDelegationActionDto = "delegate" | "run_status" | "cancel_run" | "accept_delivery" | "reject_delivery";
