// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlSelectedTaskOperatorActionGateSourceCountsDto = { readiness_actions: number, task_command_candidates: number, blocked_actions: number, read_only_actions: number, deferred_actions: number, evidence_refs: number, blocker_refs: number, };
