// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlTaskReadinessSourceCountsDto = { task_records: number, work_item_evidence_refs: number, timeline_evidence_refs: number, validation_command_refs: number, };
