// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable sanitized rejection for read-only command results.
 */
export type ControlReadOnlyCommandRejectionDto = { "kind": "host_readiness_blocked", blockers: number, } | { "kind": "runner_rejected", reasons: Array<string>, } | { "kind": "spawn_failed", reason: string, };
