// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DurableOutcomePersistenceDiagnosticDto = { persistence_id: string, handoff_id: string, command_id: string, dispatch_attempt_id: string, write_attempt_id: string, live_executor_outcome_id: string, runtime_receipt_id: string, status: string, blockers: Array<string>, evidence_refs: Array<string>, provider_write_executed: boolean, provider_material_exposed: boolean, task_mutation_permitted: boolean, next_action: string, };
