// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableProviderExecutorDispatchAdmissionDiagnosticDto } from "./DurableProviderExecutorDispatchAdmissionDiagnosticDto";
import type { DurableProviderExecutorDispatchOutcomeLinkageDiagnosticDto } from "./DurableProviderExecutorDispatchOutcomeLinkageDiagnosticDto";
import type { DurableProviderExecutorDispatchSelectionDiagnosticDto } from "./DurableProviderExecutorDispatchSelectionDiagnosticDto";

/**
 * Client-safe diagnostics for durable provider executor dispatch state.
 */
export type DurableProviderExecutorDispatchDiagnosticsDto = { selections: Array<DurableProviderExecutorDispatchSelectionDiagnosticDto>, admissions: Array<DurableProviderExecutorDispatchAdmissionDiagnosticDto>, linkages: Array<DurableProviderExecutorDispatchOutcomeLinkageDiagnosticDto>, record_count: number, client_can_execute_provider_write: boolean, client_can_mutate_tasks: boolean, provider_material_exposed: boolean, };
