// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One dispatch admission visible to diagnostics clients.
 */
export type DurableProviderExecutorDispatchAdmissionDiagnosticDto = { admission_id: string, selection_id: string, command_id: string, dispatch_attempt_id: string, provider_instance_id: string, runtime_session_ref: string, write_attempt_id: string, idempotency_key: string, status: string, blockers: Array<string>, evidence_refs: Array<string>, provider_write_executed: boolean, provider_material_exposed: boolean, task_mutation_permitted: boolean, next_action: string, };
