// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One durable executor command visible to diagnostics clients.
 */
export type DurableProviderExecutorCommandDiagnosticDto = { command_id: string, lane: string, lane_admission_id: string, provider_instance_id: string, runtime_session_ref: string, write_attempt_id: string, idempotency_key: string, method: string, status: string, blockers: Array<string>, evidence_refs: Array<string>, operator_confirmation_ref: string | null, provider_write_executed: boolean, provider_material_exposed: boolean, task_mutation_permitted: boolean, review_acceptance_permitted: boolean, next_action: string, };
