// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DurableInvocationPreflightDiagnosticDto = { preflight_id: string, command_id: string, dispatch_attempt_id: string, write_attempt_id: string, status: string, blockers: Array<string>, evidence_refs: Array<string>, next_action: string, };
