// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableProviderExecutorCommandDiagnosticDto } from "./DurableProviderExecutorCommandDiagnosticDto";
import type { DurableProviderExecutorDispatchDiagnosticsDto } from "./DurableProviderExecutorDispatchDiagnosticsDto";
import type { DurableProviderExecutorInvocationDiagnosticsDto } from "./DurableProviderExecutorInvocationDiagnosticsDto";
import type { DurableProviderExecutorStatusDiagnosticDto } from "./DurableProviderExecutorStatusDiagnosticDto";

/**
 * Client-safe diagnostics for durable provider executor command state.
 */
export type DurableProviderExecutorDiagnosticsDto = { commands: Array<DurableProviderExecutorCommandDiagnosticDto>, statuses: Array<DurableProviderExecutorStatusDiagnosticDto>, dispatch: DurableProviderExecutorDispatchDiagnosticsDto, invocation: DurableProviderExecutorInvocationDiagnosticsDto, client_can_execute_provider_write: boolean, client_can_mutate_tasks: boolean, client_can_accept_review: boolean, client_can_answer_callbacks: boolean, client_can_interrupt_provider: boolean, client_can_resume_provider: boolean, client_can_promote_replacement_thread: boolean, client_can_mutate_scm: boolean, provider_material_exposed: boolean, source_status: string, source_summary: string | null, };
