// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accepted-memory apply family: no memory, projection, scm, provider, or
 * scheduling effects ran.
 */
export type MemoryApplyNoEffects = { active_memory_apply_performed: boolean, projection_write_performed: boolean, scm_effect_performed: boolean, embedding_available: boolean, provider_sync_available: boolean, automatic_extraction_performed: boolean, task_mutation_performed: boolean, agent_scheduling_performed: boolean, ui_effect_performed: boolean, };
