// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScmCommandAdmissionDiagnosticDto = { command_id: string, status: string, required_capability: string, executes_provider_command: boolean, };
