// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScmSessionPlanDiagnosticDto = { session_id: string, repository_id: string, provider_kind: string, mode: string, status: string, user_can_test_in_known_directory: boolean, runtime_constraints: Array<string>, };
