// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScmCommandAdmissionDiagnosticDto } from "./ScmCommandAdmissionDiagnosticDto";
import type { ScmSessionPlanDiagnosticDto } from "./ScmSessionPlanDiagnosticDto";
import type { ScmWorkItemLinkDiagnosticDto } from "./ScmWorkItemLinkDiagnosticDto";

/**
 * SCM session diagnostics read model.
 */
export type ScmSessionDiagnosticsDto = { sessions: Array<ScmSessionPlanDiagnosticDto>, admissions: Array<ScmCommandAdmissionDiagnosticDto>, work_item_links: Array<ScmWorkItemLinkDiagnosticDto>, client_can_mutate_working_copy: boolean, source_status: string, source_summary: string | null, };
