// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScmWorkItemLinkDiagnosticDto = { link_id: string, task_id: string, work_item_id: string, work_session_id: string, session_command_ids: Array<string>, change_refs: Array<string>, checkpoint_ids: Array<string>, diff_summary_ids: Array<string>, requires_repair: boolean, };
