// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StewardCommandOutcomeDiagnosticDto = { command_id: string, status: string, terminal: boolean, proposal_refs: Array<string>, sync_assistance_refs: Array<string>, };
