// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StewardProposalDiagnosticDto = { proposal_id: string, kind: string, review: string, requires_human_approval: boolean, evidence_refs: Array<string>, receipt_refs: Array<string>, summary: string | null, };
