// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncRepairDiagnosticDto = { proposal_id: string, kind: string, review: string, file_ref: string, preserves_incoming_record: boolean, };
