// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncAssistanceDiagnosticDto } from "./SyncAssistanceDiagnosticDto";
import type { SyncCapturePrepDiagnosticDto } from "./SyncCapturePrepDiagnosticDto";
import type { SyncPlanDiagnosticDto } from "./SyncPlanDiagnosticDto";
import type { SyncRepairDiagnosticDto } from "./SyncRepairDiagnosticDto";

/**
 * Management sync diagnostics read model.
 */
export type SyncDiagnosticsDto = { plans: Array<SyncPlanDiagnosticDto>, repairs: Array<SyncRepairDiagnosticDto>, assistance_routes: Array<SyncAssistanceDiagnosticDto>, capture_preps: Array<SyncCapturePrepDiagnosticDto>, client_can_mutate_provider: boolean, source_status: string, source_summary: string | null, };
