// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAgentWorkUnitIssueDto } from "./TaskAgentWorkUnitIssueDto";

export type TaskAgentWorkUnitDiagnosticDto = { work_item_id: string, project_id: string, task_id: string, runtime: string, review: string, last_source_id: string, last_cursor: string, source_count: number, session_id: string | null, turn_ids: Array<string>, receipt_ids: Array<string>, checkpoint_ids: Array<string>, diff_summary_ids: Array<string>, timeline_entry_ids: Array<string>, validation_refs: Array<string>, artifact_refs: Array<string>, issues: Array<TaskAgentWorkUnitIssueDto>, summary: string, };
