[package]
name = "nucleus-agent-adapters"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
futures-executor = "0.3"
serde_json = "1"
nucleus-agent-protocol = { path = "../nucleus-agent-protocol" }
swallowtail-adapter-codex = { git = "https://github.com/inflatable-cookie/swallowtail", tag = "v0.3.2" }
swallowtail-core = { git = "https://github.com/inflatable-cookie/swallowtail", tag = "v0.3.2" }
swallowtail-host-local = { git = "https://github.com/inflatable-cookie/swallowtail", tag = "v0.3.2" }
swallowtail-idioms = { git = "https://github.com/inflatable-cookie/swallowtail", tag = "v0.3.2" }
swallowtail-runtime = { git = "https://github.com/inflatable-cookie/swallowtail", tag = "v0.3.2" }
uuid = { version = "1", features = ["v4"] }
